/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.str.simulation.rpstourney;

/**
 * @author Spencer Lee
 * The driver class for this project.
 */
public class App {
	
    /**
     * @param args Arguments for execution.
     */
    public static void main(String[] args) {
    	ILogger logger = new ConsoleLogger();
    	
    	Game game;
    	if(args.length > 0)
    	{
    		game = new Game(logger, Integer.parseInt(args[0]));
    	}
    	else
    	{
    		game = new Game(logger);
    	}
        game.runTournament();
    }
}
