/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.str.simulation.rpstourney;

public class App {

	
    public static void main(String[] args) {
    	ILogger logger = new ConsoleLogger();
        (new Game(logger)).runTournament();
    }
}
